databases:
  - name: distress-detection
    plan: starter
    databaseName: distress-detection
    user: distress_detection_user

services:
  - type: web
    name: road-pothole-detector
    runtime: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet --workers 1 --bind 0.0.0.0:$PORT "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: distress-detection
          property: internalConnectionString
disks:
  - name: data-storage
    mountPath: /data
    sizeGB: 1
